added third session
techworkersco/twc-site-berlin pull request #31
Opened 2019-10-26 15:00 UTC by chobeat

2019-10-26 16:46 UTC, shushugah requested changes

2019-10-26 16:46 UTC, shushugah commented on _events/14.md
> +date:   2019-12-05 19:00:00 +0200
Starting October 27, the time zone offset is `+0100`

2019-10-28 16:27 UTC, chobeat commented
@shushugah can you please approve?

2019-10-28 17:22 UTC, shushugah commented
Is December 7th decided? Let's also make a facebook event and link it here

2019-10-28 17:38 UTC, merged